src/Entity/SuperClasse.php
<?php

namespace App\Entity;

use App\Repository\SuperClasseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SuperClasseRepository::class)
 */
class SuperClasse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=SousEmbranchement::class, inversedBy="superClasses")
     */
    private $sous_embranchement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vernaculaire;

    /**
     * @ORM\ManyToOne(targetEntity=Embranchement::class, inversedBy="superClasses")
     */
    private $embranchement;

    /**
     * @ORM\OneToMany(targetEntity=Classe::class, mappedBy="superClasse")
     */
    private $classes;

    public function __construct()
    {
        $this->classes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSousEmbranchement(): ?SousEmbranchement
    {
        return $this->sous_embranchement;
    }

    public function setSousEmbranchement(?SousEmbranchement $sous_embranchement): self
    {
        $this->sous_embranchement = $sous_embranchement;

        return $this;
    }

   
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVernaculaire(): ?string
    {
        return $this->vernaculaire;
    }

    public function setVernaculaire(?string $vernaculaire): self
    {
        $this->vernaculaire = $vernaculaire;

        return $this;
    }

    public function getEmbranchement(): ?Embranchement
    {
        return $this->embranchement;
    }

    public function setEmbranchement(?Embranchement $embranchement): self
    {
        $this->embranchement = $embranchement;

        return $this;
    }

    /**
     * @return Collection|Classe[]
     */
    public function getClasses(): Collection
    {
        return $this->classes;
    }

    public function addClass(Classe $class): self
    {
        if (!$this->classes->contains($class)) {
            $this->classes[] = $class;
            $class->setSuperClasse($this);
        }

        return $this;
    }

    public function removeClass(Classe $class): self
    {
        if ($this->classes->removeElement($class)) {
            // set the owning side to null (unless already changed)
            if ($class->getSuperClasse() === $this) {
                $class->setSuperClasse(null);
            }
        }

        return $this;
    }
}

src/Form/SuperClasseType.php
<?php

namespace App\Form;

use App\Entity\SuperClasse;
use App\Entity\SousEmbranchement;
use App\Entity\Embranchement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SuperClasseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('vernaculaire')
            ->add('sous_embranchement', EntityType::class, [
                'class' => SousEmbranchement::class,
                'choice_label' => 'nom',
                'multiple' => false,
                'mapped' => true,
                'required' => false, ])
            ->add('embranchement', EntityType::class, [
                'class' => Embranchement::class,
                'choice_label' => 'nom',
                'multiple' => false,
                'mapped' => true,
                'required' => false, ])
        ;
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SuperClasse::class,
        ]);
    }
}

src/Controller/SuperClasseController.php
<?php

namespace App\Controller;

use App\Entity\SuperClasse;
use App\Form\SuperClasseType;
use App\Repository\SuperClasseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/super/classe")
 */
class SuperClasseController extends AbstractController
{
    /**
     * @Route("/", name="super_classe_index", methods={"GET"})
     */
    public function index(SuperClasseRepository $superClasseRepository): Response
    {
        return $this->render('super_classe/index.html.twig', [
            'super_classes' => $superClasseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="super_classe_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $superClasse = new SuperClasse();
        $form = $this->createForm(SuperClasseType::class, $superClasse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($superClasse);
            $entityManager->flush();

            return $this->redirectToRoute('super_classe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('super_classe/new.html.twig', [
            'super_classe' => $superClasse,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="super_classe_show", methods={"GET"})
     */
    public function show(SuperClasse $superClasse): Response
    {

        return $this->render('super_classe/show.html.twig', [
            'super_classe' => $superClasse,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="super_classe_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, SuperClasse $superClasse): Response
    {
        $form = $this->createForm(SuperClasseType::class, $superClasse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('super_classe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('super_classe/edit.html.twig', [
            'super_classe' => $superClasse,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="super_classe_delete", methods={"POST"})
     */
    public function delete(Request $request, SuperClasse $superClasse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$superClasse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($superClasse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('super_classe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/super_classe/_delete_form.html.twig
<form method="post" action="{{ path('super_classe_delete', {'id': super_classe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ super_classe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/super_classe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SuperClasse{% endblock %}

{% block content %}
    <h1>Edit SuperClasse</h1>

    {{ include('super_classe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('super_classe_index') }}">back to list</a>

    {{ include('super_classe/_delete_form.html.twig') }}
{% endblock %}

templates/super_classe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SuperClasse index{% endblock %}

{% block content %}
    <h1>SuperClasse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Vernaculaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for super_classe in super_classes %}
            <tr>
                <td>{{ super_classe.id }}</td>
                <td>{{ super_classe.nom }}</td>
                <td>{{ super_classe.vernaculaire }}</td>
                <td>
                    <a href="{{ path('super_classe_show', {'id': super_classe.id}) }}">show</a>
                    <a href="{{ path('super_classe_edit', {'id': super_classe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('super_classe_new') }}">Create new</a>
{% endblock %}

templates/super_classe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SuperClasse{% endblock %}

{% block content %}
    <h1>Create new SuperClasse</h1>

    {{ include('super_classe/_form.html.twig') }}

    <a href="{{ path('super_classe_index') }}">back to list</a>
{% endblock %}

templates/super_classe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SuperClasse{% endblock %}

{% block content %}
    <h1>Super-classe des {{ super_classe.nom }} {% if (super_classe.vernaculaire is defined and super_classe.vernaculaire != "") %}({{ super_classe.vernaculaire }})
        {% endif %}  <br/> 
        {% if super_classe.sousEmbranchement is defined and super_classe.sousEmbranchement != null%}sous-Embranchement des {{ super_classe.sousEmbranchement.nom }}, 
        {% endif %} 
       
     {% if super_classe.embranchement is defined and super_classe.embranchement!=null %}Embranchement des {{ super_classe.embranchement.nom }}{% endif %}
   
     </h1>

     <ul>
        {% for Classe in super_classe.Classes %}
            
            <li>

               <a href="{{ path('classe_show', {'id': Classe.id}) }}"><h2>Classe des {{ Classe.nom }} {% if (Classe.vernaculaire is defined and Classe.vernaculaire != "") %}({{ Classe.vernaculaire }}){% endif %}</h2></a>
               <ul>
                {% for sousClasse in Classe.sousClasses %}
                <li> <a href="{{ path('sous_classe_show', {'id': sousClasse.id}) }}"><h2>Sous-classe des {{ sousClasse.nom }} {% if (sousClasse.vernaculaire is defined and sousClasse.vernaculaire != "" ) %}({{ sousClasse.vernaculaire }}){% endif %}</h2></a></li>
                 {% endfor %}
               </ul>
            </li>
            {% endfor %}
        </ul>

    <a href="{{ path('super_classe_index') }}">back to list</a>

    <a href="{{ path('super_classe_edit', {'id': super_classe.id}) }}">edit</a>

    {{ include('super_classe/_delete_form.html.twig') }}
{% endblock %}